---
# Variables:
# - var_workingDir
# - var_domainPrivateKey
# - var_domainUser
# - var_hosts
#
# Requirements: 
#

# ------------------------------
#  Prepare host connection
# ------------------------------
- name: Prepare fabric connection
  hosts: localhost
  connection: local
  tasks:
    - name: Create working dir
      file:
        path: "{{ var_workingDir }}"
        state: directory

    - name: Set domain private key path
      when: var_domainPrivateKey is defined
      set_fact: 
        var_domainPrivateKeyPath: "{{ var_workingDir }}/{{ ansible_date_time.epoch | int | random | to_uuid }}" 

    - name: Write temporal domain private key locally
      when: var_domainPrivateKey is defined
      copy:
        content: "{{ var_domainPrivateKey }}"
        dest: "{{ var_domainPrivateKeyPath }}"
        mode: "600"

    - name: Add in-mem host
      add_host:
        name: host
        ansible_host: "{{ item }}"
        ansible_user: "{{ var_domainUser }}"
        ansible_ssh_private_key_file: "{{ var_domainPrivateKeyPath }}"
      changed_when: false
      loop: "{{ var_hosts.split(',') }}"

# ------------------------------
#  Add master
# ------------------------------
- name: Add master
  hosts: "{{ var_hosts }}"
  tasks:

    - name: Install Docker
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "{{ item }}"
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install docker-ce
      apt: 
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli 
        - containerd.io



# ------------------------------
#  Clean-up fabric connection
# ------------------------------
- name: Clean-up fabric connection
  hosts: localhost
  connection: local
  tasks:
    - name: Delete domain private key
      when: var_domainPrivateKey is defined
      file: 
        path: "{{ var_domainPrivateKeyPath }}"
        state: absent

    - name: Delete domain public key
      when: var_domainPublicKey is defined
      file: 
        path: "{{ var_domainPrivateKeyPath }}.pub"
        state: absent