---
# Variables:
# - var_workingDir
# - var_domainPrivateKey
# - var_domainUser:
# - var_fabricHost: 
#
# Requirements: 
#

# ------------------------------
#  Prepare fabric connection
# ------------------------------
- name: Prepare fabric connection
  hosts: localhost
  connection: local
  tasks:
    - name: Create working dir
      file:
        path: "{{ var_workingDir }}"
        state: directory

    - name: Set domain private key path
      when: var_domainPrivateKey is defined
      set_fact: 
        var_domainPrivateKeyPath: "{{ var_workingDir }}/{{ ansible_date_time.epoch | int | random | to_uuid }}" 

    - name: Write temporal domain private key locally
      when: var_domainPrivateKey is defined
      copy:
        content: "{{ var_domainPrivateKey }}"
        dest: "{{ var_domainPrivateKeyPath }}"
        mode: "600"

    - name: Add in-mem host
      add_host:
        name: fabric
        ansible_host: "{{ var_fabricHost }}"
        ansible_user: "{{ var_domainUser }}"
        ansible_ssh_private_key_file: "{{ var_domainPrivateKeyPath }}"
      changed_when: false

# ------------------------------
#  Remove fabric
# ------------------------------
- name: Remove fabric
  hosts: fabric
  tasks:

    - name: Remove domain user
      become: yes
      ignore_errors: yes   # because the current user is deleted !
      user:
        name: "{{ var_domainUser }}"
        state: absent
        remove: yes
        force: yes

# ------------------------------
#  Clean-up fabric connection
# ------------------------------
- name: Clean-up fabric connection
  hosts: localhost
  connection: local
  tasks:
    - name: Delete domain private key
      when: var_domainPrivateKey is defined
      file: 
        path: "{{ var_domainPrivateKeyPath }}"
        state: absent