FROM node:16
LABEL org.opencontainers.image.authors="jesparza@dsic.upv.es"
LABEL description="Komponents Dashboard"
EXPOSE 8080

COPY dashboard /app/dashboard/

WORKDIR /app/dashboard

RUN npm install

ENTRYPOINT npm run serve
