FROM node:16
LABEL org.opencontainers.image.authors="jesparza@dsic.upv.es"
LABEL description="Komponents Realm Controller"
EXPOSE 8000

COPY realmcontroller /app/realmcontroller/
COPY store /app/store/
COPY utils /app/utils/

RUN cd /app/utils && npm install
RUN cd /app/store && npm install

WORKDIR /app/realmcontroller

RUN npm install

ENTRYPOINT node src/cli start
