kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: {{ var_domainId | default('komponents') }}
networking:
  apiServerAddress: "{{ var_hostAddr }}"
  apiServerPort: 6443
#  podSubnet: "10.244.0.0/16"
#  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  # inject external traffic to the cluster
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   listenAddress: "{{ var_hostAddr }}"
  #   protocol: TCP