



# Ansible
#apt-get install ansible
# 
#ansible-galaxy collection install community.general
# Required for adding public keys to authorized_keys
#ansible-galaxy collection install ansibe.posix
# Required for docker commands
#ansible-galaxy collection install community.docker
# Required for managing k8s api
#ansible-galaxy collection install community.kubernetes

# Install kubectl for controlling k8s clusters
